### ISSUE TITLE
Fails to create html output if VCF contains BND between main and alt chromosome (NullPointerException)

### ISSUE THREAD

**Issue by james-lawlor** [TheJacksonLaboratory/SvAnna#189]
Hi,
I've  been trying out SvAnna after seeing the preprint and I noticed that if a VCF contains a BND between a hg38 main and alternate/decoy/random contig, SvAnna will return a NullPointerException when attempting to write the html output. (The VCF output is properly created, and the CSV output can only be created if the html output is turned off. )

See example variant(s) below. Either BND in the pair will trigger the issue.

```console
$ cat main-alt-bnd.vcf
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=2021-06-03T02:03:58.262Z
##source=pbsv 2.6.0 (commit v2.4.1-155-g281bd17)
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the structural variant described in this record">
##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=SVANN,Number=.,Type=String,Description="Repeat annotation of structural variant">
##INFO=<ID=CIPOS,Number=2,Type=Integer,Description="Confidence interval around POS for imprecise variants">
##INFO=<ID=MATEID,Number=.,Type=String,Description="ID of mate breakends">
##INFO=<ID=MATEDIST,Number=1,Type=Integer,Description="Distance to the mate breakend for mates on the same contig">
##INFO=<ID=IMPRECISE,Number=0,Type=Flag,Description="Imprecise structural variation">
##INFO=<ID=SHADOWED,Number=0,Type=Flag,Description="CNV overlaps with or is encapsulated by deletion">
##ALT=<ID=INV,Description="Inversion">
##ALT=<ID=DUP,Description="Duplication">
##ALT=<ID=CNV,Description="Copy number variable region">
##FILTER=<ID=Decoy,Description="Variant involves a decoy sequence">
##FILTER=<ID=NearReferenceGap,Description="Variant is near (< 1000 bp) from a gap (run of >= 50 Ns) in the reference assembly">
##FILTER=<ID=NearContigEnd,Description="Variant is near (< 1000 bp) from the end of a contig">
##FILTER=<ID=InsufficientStrandEvidence,Description="Variant has insufficient number of reads per strand (< 1).">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Read depth per allele">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read depth at this position for this sample">
##FORMAT=<ID=SAC,Number=.,Type=Integer,Description="Number of reads on the forward and reverse strand supporting each allele including reference">
##FORMAT=<ID=CN,Number=1,Type=Integer,Description="Copy number genotype for imprecise events">
##INFO=<ID=NotFullySpanned,Number=0,Type=Flag,Description="Duplication variant does not have any fully spanning reads">
##contig=<ID=chr16,length=90338345>
##contig=<ID=chr16_KI270856v1_alt,length=63982>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
chr16	1871875	pbsv.BND.chr16:1871875-chr16_KI270856v1_alt:58	C	C[chr16_KI270856v1_alt:58[	.	NearContigEnd	SVTYPE=BND;CIPOS=-56,20;MATEID=pbsv.BND.chr16_KI270856v1_alt:58-chr16:1871875	GT:AD:DP	0/1:9,8:17
chr16_KI270856v1_alt	58	pbsv.BND.chr16_KI270856v1_alt:58-chr16:1871875	T	]chr16:1871875]T	.	NearContigEnd	SVTYPE=BND;CIPOS=-57,19;MATEID=pbsv.BND.chr16:1871875-chr16_KI270856v1_alt:58	GT:AD:DP	0/1:3,8:11



$ java -jar ./svanna-cli-1.0.0-RC2/svanna-cli-1.0.0-RC2.jar prioritize --config./svanna-cli-1.0.0-RC2/svanna-config.yml --output-format html,csv,vcf --vcf main-alt-bnd.vcf

  ____         _
 / ___|__   __/ \   _ __  _ __   __ _
 \___ \\ \ / / _ \ | '_ \| '_ \ / _` |
  ___) |\ V / ___ \| | | | | | | (_| |
 |____/  \_/_/   \_\_| |_|_| |_|\__,_|


18:43:31.381 INFO  org.jax.svanna.cli.Main - Starting Main v1.0.0-RC2 using Java 11.0.12 on hpc0005 with PID 59489 (./svanna-cli-1.0.0-RC2/svanna-cli-1.0.0-RC2.jar started by jlawlor in.)
18:43:31.386 INFO  org.jax.svanna.cli.Main - No active profile set, falling back to default profiles: default
18:43:35.806 INFO  o.j.s.a.SvannaAutoConfiguration - Reading transcript definitions from `./svanna-cli-1.0.0-RC2/hg38_refseq.ser`
18:43:49.728 INFO  o.j.s.a.SvannaAutoConfiguration - Spooling up SvAnna v1.0.0-RC2 using resources in `./svanna-cli-1.0.0-RC2/svanna`
18:44:11.939 INFO  org.jax.svanna.cli.Main - Started Main in 42.55 seconds (JVM running for 45.735)
18:44:11.951 INFO  o.j.svanna.cli.cmd.PrioritizeCommand - Reading variants from `main-alt-bnd.vcf`
18:44:12.131 INFO  o.j.svanna.cli.cmd.PrioritizeCommand - Read 2 variants
18:44:12.131 INFO  o.j.svanna.cli.cmd.PrioritizeCommand - Filtering out the variants with reciprocal overlap >80.0% occurring in more than 1.0% probands
18:44:12.131 INFO  o.j.svanna.cli.cmd.PrioritizeCommand - Filtering out the variants where ALT allele is supported by less than 3 reads
18:44:22.930 INFO  o.j.svanna.cli.cmd.PrioritizeCommand - Prioritizing variants
18:44:23.055 INFO  o.j.s.cli.writer.vcf.VcfResultWriter - Writing VCF results into ./main-alt-bnd.SVANNA.vcf.gz
18:44:23.145 INFO  o.j.s.c.writer.html.HtmlResultWriter - Writing HTML results to ./main-alt-bnd.SVANNA.html
java.lang.NullPointerException
	at org.jax.svanna.core.overlap.IntervalArrayGeneOverlapper.emptyRegionResults(IntervalArrayGeneOverlapper.java:96)
	at org.jax.svanna.core.overlap.IntervalArrayGeneOverlapper.translocationOverlaps(IntervalArrayGeneOverlapper.java:84)
	at org.jax.svanna.core.overlap.IntervalArrayGeneOverlapper.getOverlaps(IntervalArrayGeneOverlapper.java:46)
	at org.jax.svanna.cli.writer.html.VisualizableGeneratorSimple.prepareLandscape(VisualizableGeneratorSimple.java:47)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.jax.svanna.cli.writer.html.HtmlResultWriter.write(HtmlResultWriter.java:64)
	at org.jax.svanna.cli.cmd.PrioritizeCommand.runAnalysis(PrioritizeCommand.java:333)
	at org.jax.svanna.cli.cmd.PrioritizeCommand.call(PrioritizeCommand.java:223)
	at org.jax.svanna.cli.cmd.PrioritizeCommand.call(PrioritizeCommand.java:44)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at org.jax.svanna.cli.Main.main(Main.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

$ zgrep -v "^#" main-alt-bnd.SVANNA.vcf.gz
chr16	1871875	pbsv.BND.chr16:1871875-chr16_KI270856v1_alt:58	C	C[chr16_KI270856v1_alt:58[	.	NearContigEnd	CIPOS=-56,20;MATEID=pbsv.BND.chr16_KI270856v1_alt:58-chr16:1871875;SVTYPE=BND;TADSV=0.00	GT:AD:DP	0/1:9,8:17
chr16_KI270856v1_alt	58	pbsv.BND.chr16_KI270856v1_alt:58-chr16:1871875	T	]chr16:1871875]T	.	NearContigEnd	CIPOS=-57,19;MATEID=pbsv.BND.chr16:1871875-chr16_KI270856v1_alt:58;SVTYPE=BND;TADSV=0.00	GT:AD:DP	0/1:3,8:11
```

I've found that removing those variants using `bcftools filter -e 'INFO/MATEID~"alt" || INFO/MATEID~"random" || INFO/MATEID~"decoy" || INFO/MATEID~"Un"' input.vcf.gz` is sufficient to properly generate the html, though it would be preferable for SvAnna to skip these events if necessary.

**Comment by ielis** [comment]
Hi @james-lawlor ,
thanks a lot for letting us know about the bug and for providing all the information that made it very easy to trace the source. I fixed the null pointer and I'll be making another release candidate (RC3) with the updated code soon.

The transcript databases we use in SvAnna do not define any gene/transcript annotated to non-primary contigs of the genome assembly (ALT, unplaced, etc.). Therefore, SvAnna does not produce a lot of meaningful output for such variants right now. 
Still, the code should be able to handle such variants and I prefer not to drop the variants that involve non-primary contigs. As you pointed out, it is easy to do so prior running SvAnna. 

The updated code will generate a translocation SVG even for a translocation that involves non-primary contig, The SVG panel for non-primary breakend will, however, be empty, as there are no genes to draw.

I hope this sounds OK to you.
Thanks and cheers,
Daniel

**Comment by james-lawlor** [comment]
@ielis - That sounds great! Agree that it's better to show something less informative than dropping the variants entirely.
